[workspace]
resolver = "2"
members = ["crates/apios-core", "crates/apios"]

[workspace.package]
version = "0.2.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/zixij644-elaborate/ApiosCleaner"
readme = "README.md"
homepage = "https://github.com/zixij644-elaborate/ApiosCleaner"

[profile.release]
lto = true
